Print Hello World to console
JaysGitLab/cs-5666-greeting-whereswaldon pull request #2
Opened 2017-02-01 00:03 UTC by whereswaldon

This requirement was difficult to implement and required much thought.
I hope that the customer understands just how much development time
that they wasted by choosing such difficult requirements.

Closes #1

2017-02-01 02:40 UTC, fenwickjb commented
Would be better if testing were automated and not relying on humans who are error-prone. ;-)
Check this out...
http://stackoverflow.com/questions/1119385/junit-test-for-system-out-println

Also, it might help if you assign me as a "reviewer" (see panel to the right).

2017-02-01 02:40 UTC, fenwickjb requested changes

2017-02-01 02:40 UTC, fenwickjb commented on Hello.java
> +		System.out.println("Hello, world!");
The printed string does not meet the specification.

2017-02-01 04:00 UTC, whereswaldon commented on Hello.java
> +		System.out.println("Hello, world!");
Agreed, but it does now.

2017-02-03 14:18 UTC, fenwickjb approved these changes

2017-02-03 14:19 UTC, merged